# SPDX-License-Identifier: GPL-2.0-only

mdev-y := mdev_core.o mdev_sysfs.o mdev_driver.o

obj-$(CONFIG_VFIO_MDEV) += mdev.o
obj-$(CONFIG_VFIO_MDEV_DEVICE) += vfio_mdev.o

# kvmgt depends on mdev, replace it with dummy driver
ifeq ($(CONFIG_VFIO_MDEV),m)
obj-$(CONFIG_DRM_I915_GVT_KVMGT) += kvmgt.o
kvmgt-y := kvmgt_dummy.o
endif
